apiVersion: v1
kind: Service
metadata:
  name: srin-api-express-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: srin-api-express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
